### ISSUE TITLE
convertible_intake returns success even on errors

### ISSUE THREAD

**Issue by AardWolf** [mh-community-tools/mh-hunt-helper#111]
SQL executions should have try/catch blocks so exceptions are returned to the end user as an error response.

**Comment by tehhowch** [comment]
I think the always-success notification is to prevent trial-by-error determination of how to spoof submissions

**Comment by AardWolf** [comment]
OK, valid use-case but is there some way we can flag that there's a problem? Without adding something like Splunk into the stack, ideally.

**Comment by DevJackSmith** [comment]
i think i usually send an error to error.log in nginx, that way one look at the log tells me what's going on.

**Comment by DevJackSmith** [comment]
but yes, this is by design, i don't want to give spoofers any info.
