### ISSUE TITLE
Deferred styles in common_footer.php causing FOUC

### ISSUE THREAD

**Issue by tsitu** [mh-community-tools/mh-hunt-helper#138]
The deferred styles pattern being used in `common_footer.php` is causing [FOUC](https://en.wikipedia.org/wiki/Flash_of_unstyled_content) on every page.

I understand this pattern slightly improves initial page load times, but it's not so great for UX.

![mhctfouc](https://user-images.githubusercontent.com/6689581/97925413-31632800-1d16-11eb-9161-8c2ac358a3af.gif)

Should we move the stylesheets to `common_head.php` instead?

**Comment by DevJackSmith** [comment]
i agree this is an issue, i think i did it this way to satisfy google test in one category, while it broke another. https://developers.google.com/speed/pagespeed/insights/?url=agiletravels.com

**Comment by tsitu** [comment]
Before and after: Lighthouse tests on the changes in https://github.com/mh-community-tools/mh-hunt-helper/pull/146

![atperf1](https://user-images.githubusercontent.com/6689581/103330516-ae5d0600-4a16-11eb-8198-1d2aaf52143b.PNG)
![atperf2](https://user-images.githubusercontent.com/6689581/103330519-af8e3300-4a16-11eb-8ba7-b55d10b3ff97.PNG)
