### ISSUE TITLE
some mice break accordion

### ISSUE THREAD

**Issue by paulkarnowski** [mh-community-tools/mh-hunt-helper#164]
On the map helper, searching for "corky, the collector" will prevent any of the Queso Geyser accordions from opening. A JS error occurs when an accordion button is clicked. It is caused by the href "collapseThreeOne61...", because the periods aren't escaped by a "\\"

**Comment by paulkarnowski** [comment]
A possible solution is to change the href to "#collapseThreeOne61\.\.\."

From a business standpoint, what stage is "..." supposed to be? Is it valid? Could this also be a data issue?

**Comment by DevJackSmith** [comment]
so it's not corky the collector, i believe it might be Flamin' Queso or something else, since cork defender also breaks it

**Comment by DevJackSmith** [comment]
this is a weird bug needs some more investigating. The triple dot is normal and is used in other results when there's no specific stage. But unlike other results it usually is not together with stages (either the location has stages or it doesn't, there should be no triple dot with other stages in one location usually).

Another observation is that if we change display from none to block to expand the collapse class, everything displays correctly. So the only thing not working is the javascript that expands it. Exact error being:

`Syntax error, unrecognized expression: #collapseThreeOne61...`

**Comment by DevJackSmith** [comment]
changing triple dot to "any" works, thanks going to make a fix here shortly
