### ISSUE TITLE
A view that shows fastest way to get an item

### ISSUE THREAD

**Issue by DevJackSmith** [mh-community-tools/mh-hunt-helper#74]
current drop rate accounts for amount of items dropped, so if a person gets 1 item in 10 hunts or 10 items in 100 hunts, the rate stays the same. However it is useful to see the fastest way to get an item, especially if you just need one.

**Comment by AardWolf** [comment]
Coded in drop_chance branch - chance to drop an item, a new sortable column

**Comment by tsitu** [comment]
Added in #115
