### ISSUE TITLE
create scavenger map helper tool

### ISSUE THREAD

**Issue by DevJackSmith** [mh-community-tools/mh-hunt-helper#77]
after the collector is updated to collect scavenger data #76, we want to have a tool which helps people collect items for scavenger map the fastest.

- only need 1 quantity of each item = no need avg drop quantity, just any quantity 1 or more.
- might still want to group results by location -> stages
- might still want to show cheese for those mice
- might want to show avg hunts it takes to get the drop from the mouse or some kind of rate
- might want to show items with rate drop in a location+stage instead of specific mouse?

**Comment by groupsky** [comment]
@DevJackSmith I suggest as a quick step to add drop chance to [loot tool](https://mhhunthelper.agiletravels.com/loot.php)

**Comment by DevJackSmith** [comment]
great idea, i like it

**Comment by AardWolf** [comment]
drops table needs two columns added. Let's call them `drop_count` and `drop_chance_per_catch`.

Update the `update_drops procedure`:

first insert statement adds drop_count column to list of columns.
select statement adds `COUNT(hl.amount)` to select list.
update statement sets drop_chance_per_catch to drop_count / total_hunts.

**Comment by tsitu** [comment]
Drop chance has been added in #115, is this enough to close?

**Comment by DevJackSmith** [comment]
it's a great step towards it. Thanks for creating it. When i created this ticket i was thinking something like we have for map helper, where we can paste a list of items needed for scavenger map and then the tool would give locations where these items drop, with locations that have the most unique items being at the top. (Just like map helper tool for mice, only instead of mice it's items).

**Comment by DevJackSmith** [comment]
created scavenger helper
